import { Component, OnInit } from '@angular/core';
import { FilterField } from 'main/app/ui-components/dynamic-crud/dynamic-crud.models';
import { FormFieldBase, FormFieldType, SubForm } from 'main/app/ui-components/dynamic-form/dynamic-form.models';
import { InfoField, InfoType } from 'main/app/ui-components/dynamic-info/dynamic-info.models';
import { TableColumn } from 'main/app/ui-components/dynamic-table/dynamic-table.models';
import { BehaviorSubject } from 'rxjs';

@Component({
  selector: 'app-call',
  templateUrl: './call.component.html',
  styleUrls: ['./call.component.scss']
})
export class CallComponent implements OnInit {

  constructor() { }

  // inquiry1 : SubForm = new SubForm({
  //   key : 'inq1',
  //   title : 'OWNERS / REPRESENTATIVES LOG',
  //   order:300,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'position',  
  //       label : 'Position',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'name',  
  //       label : 'Name',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'arrival_port',  
  //       label : 'Arrival Port',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'arrival_date',  
  //       label : 'Arrival Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'first_hotel',  
  //       label : 'First Hotel',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'first_hotel_details',  
  //       label : 'First Hotel Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'first_hotel_room',  
  //       label : 'First Hotel Room',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'first_hotel_phone',  
  //       label : 'First Hotel Phone',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'first_hotel_checkin_date',  
  //       label : 'First Hotel Checkin Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'first_hotel_checkout_date',  
  //       label : 'First Hotel Checkout Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'second_hotel',  
  //       label : 'Second Hotel',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'second_hotel_details',  
  //       label : 'Second Hotel Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'second_hotel_room',  
  //       label : 'Second Hotel Room',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'second_hotel_phone',  
  //       label : 'Second Hotel Phone',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'second_hotel_checkin_date',  
  //       label : 'Second Hotel Checkin Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'second_hotel_checkout_date',  
  //       label : 'Second Hotel Checkout Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'visa_expiration_date',  
  //       label : 'Visa Expiration Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'passport',  
  //       label : 'Passport',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'departure_port',  
  //       label : 'Departure Port',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'departure_date',  
  //       label : 'Departure Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'departure_details',  
  //       label : 'Departure Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'comments',  
  //       label : 'Comments',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'name',
  //         text : 'Name',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'position',
  //       text : 'Position',
  //       width : 35
  //     } as TableColumn
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry2 : SubForm = new SubForm({
  //   key : 'inq2',
  //   title : 'CREW CHANGES',
  //   order:300,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'name',  
  //       label : 'Name',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
      
  //     new BehaviorSubject<FormFieldBase>({
  //       value : false,
  //       order : 2,
  //       type : FormFieldType.CheckBox, 
  //       key : 'signin_signoff',  
  //       label : 'Signin Or Signoff',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'rank',  
  //       label : 'Rank',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'details',  
  //       label : 'Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'passport_expiration_date',  
  //       label : 'Passport Expiration Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'exit_visa_application_date',  
  //       label : 'Exit Visa Application Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'passport_image',  
  //       label : 'Passport Image',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'visa_image',  
  //       label : 'Visa Image',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'exit_visa_ISS_date',  
  //       label : 'Exit Visa ISS Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'exit_visa_ISS_date',  
  //       label : 'Exit Visa ISS Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'hotel',  
  //       label : 'Hotel',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'details',  
  //       label : 'Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'room',  
  //       label : 'Room',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'phone',  
  //       label : 'Phone',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'checkin_date',  
  //       label : 'Checkin Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'checkout_date',  
  //       label : 'Checkout Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'date',  
  //       label : 'Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'name',
  //         text : 'Name',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'rank',
  //       text : 'Rank',
  //       width : 35
  //     } as TableColumn,
  //     {
  //       name : 'signin_signoff',
  //       text : 'Signin or Signoff',
  //       width : 35
  //     } as TableColumn
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry3 : SubForm = new SubForm({
  //   key : 'inq3',
  //   title : 'MEDICAL ATTENDANCE',
  //   order:300,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'type',  
  //       label : 'Type',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'type',  
  //       label : 'Type',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'equipment_surveys',  
  //       label : 'Equipment Surveys',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'hotel',  
  //       label : 'Hotel',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'details',  
  //       label : 'Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'room',  
  //       label : 'Room',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'phone',  
  //       label : 'Phone',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'referrer',  
  //       label : 'Referrer',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'referrer_details',  
  //       label : 'Referrer Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
      
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'checkin_date',  
  //       label : 'Checkin Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'checkout_date',  
  //       label : 'Checkout Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'arrival_date',  
  //       label : 'Arrival Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'departure_date',  
  //       label : 'Departure Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'departure_date',  
  //       label : 'Departure Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
      
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'arrival_flight',  
  //       label : 'Arrival Flight',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'departure_flight',  
  //       label : 'Departure Flight',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'attendance',  
  //       label : 'Attendance',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'type',
  //         text : 'Type',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'names',
  //       text : 'Names/Details',
  //       width : 35
  //     } as TableColumn
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry4 : SubForm = new SubForm({
  //   key : 'inq4',
  //   title : 'MEDICAL ATTENDANCE',
  //   order:200,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'position',  
  //       label : 'Position',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'name',  
  //       label : 'Name',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'incident_date',  
  //       label : 'Incident Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'medical_date',  
  //       label : 'Medical Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'checkin_date',  
  //       label : 'Checkin Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'checkout_date',  
  //       label : 'Checkout Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'status',  
  //       label : 'Status',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'status',  
  //       label : 'Status',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'position',
  //         text : 'Position',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'name',
  //       text : 'Name',
  //       width : 35
  //     } as TableColumn,
  //     {
  //       name : 'status',
  //       text : 'Status',
  //       width : 35
  //     } as TableColumn,
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry5 : SubForm = new SubForm({
  //   key : 'inq5',
  //   title : 'OFFLAND ITEMS FORWARDING',
  //   order:200,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'post_office',  
  //       label : 'Post Office',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'description',  
  //       label : 'Description',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'details',  
  //       label : 'Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'quantity',  
  //       label : 'Quantity',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'doclink',  
  //       label : 'Document',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'offland_date',  
  //       label : 'Offland Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),          
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'forward_date',  
  //       label : 'Forward Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'eta_datetime',  
  //       label : 'ETA Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'destination',  
  //       label : 'Destination',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'destination_details',  
  //       label : 'Destination Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'status',  
  //       label : 'Status',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
      
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'export_documents',  
  //       label : 'Export Documents',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'method',  
  //       label : 'Method',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'post_office',
  //         text : 'Post Office',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'description',
  //       text : 'Description',
  //       width : 35
  //     } as TableColumn,
  //     {
  //       name : 'status',
  //       text : 'Status',
  //       width : 35
  //     } as TableColumn,
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry6 : SubForm = new SubForm({
  //   key : 'inq6',
  //   title : 'Power Supply',
  //   order:200,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'power_supply',  
  //       label : 'Power Supply',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'quantity',  
  //       label : 'Quantity',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'datetime',  
  //       label : 'Date & Time',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'method',  
  //       label : 'Method',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'status',  
  //       label : 'Status',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
      
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'power_supply',
  //         text : 'Power Supply',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'quantity',
  //       text : 'Quantity',
  //       width : 35
  //     } as TableColumn,
  //     {
  //       name : 'status',
  //       text : 'Status',
  //       width : 35
  //     } as TableColumn,
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry7 : SubForm = new SubForm({
  //   key : 'inq7',
  //   title : 'DOMESTIC SHIPMENT',
  //   order:200,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'type',  
  //       label : 'Type',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'track_number',  
  //       label : 'Tracking Number',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'doclink',  
  //       label : 'Document',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'post_office',  
  //       label : 'Post Office',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'date',  
  //       label : 'Actual Arrival Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'status',  
  //       label : 'Status',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
      
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'type',
  //         text : 'Type',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'date',
  //       text : 'Actual Arrival Date',
  //       width : 35
  //     } as TableColumn,
  //     {
  //       name : 'status',
  //       text : 'Status',
  //       width : 35
  //     } as TableColumn,
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry8 : SubForm = new SubForm({
  //   key : 'inq8',
  //   title : 'OVERSEAS SHIPMENT',
  //   order:200,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'type',  
  //       label : 'Type',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'track_number',  
  //       label : 'Tracking Number',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'doclink',  
  //       label : 'Document',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'post_office',  
  //       label : 'Post Office',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'date',  
  //       label : 'Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'status',  
  //       label : 'Status',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase)      
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'type',
  //         text : 'Type',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'date',
  //       text : 'Actual Arrival Date',
  //       width : 35
  //     } as TableColumn,
  //     {
  //       name : 'status',
  //       text : 'Status',
  //       width : 35
  //     } as TableColumn,
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry9 : SubForm = new SubForm({
  //   key : 'inq9',
  //   title : 'STORE PROVISIONS',
  //   order:900,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'type',  
  //       label : 'Type',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'quantity',  
  //       label : 'quantity',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'supplier',  
  //       label : 'Supplier',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
      
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'details',  
  //       label : 'Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'date',  
  //       label : 'Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'method',  
  //       label : 'Method',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'status',  
  //       label : 'Status',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase)
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'type',
  //         text : 'Type',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'dlvdate',
  //       text : 'Delivery Date',
  //       width : 35
  //     } as TableColumn,
  //     {
  //       name : 'status',
  //       text : 'Status',
  //       width : 35
  //     } as TableColumn,
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry10 : SubForm = new SubForm({
  //   key : 'inq10',
  //   title : 'BUNKERS - LUBOIL CHEMS - PAINTS SUPPLY',
  //   order:200,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'type',  
  //       label : 'Type',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'quantity',  
  //       label : 'Quantity',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'date',  
  //       label : 'Delivery Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'details',  
  //       label : 'Details',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'supplier_type',  
  //       label : 'Supplier Type',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'method',  
  //       label : 'Delivery Method',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'status',  
  //       label : 'Status',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'type',
  //         text : 'Type',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'date',
  //       text : 'Delivery Date',
  //       width : 35
  //     } as TableColumn,
  //     {
  //       name : 'status',
  //       text : 'Status',
  //       width : 35
  //     } as TableColumn,
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry11 : SubForm = new SubForm({
  //   key : 'inq11',
  //   title : 'SHIP POLUTANTS',
  //   order:200,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'service',  
  //       label : 'Service',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'quantity',  
  //       label : 'Quantity',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'date',  
  //       label : 'Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'status',  
  //       label : 'Status',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //   ] as  BehaviorSubject<FormFieldBase>[],
  //   tableData : new BehaviorSubject<any[]>([]),
  //   tableColumns : [
  //     {
  //         name : 'service',
  //         text : 'Service',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'date',
  //       text : 'Date',
  //       width : 35
  //     } as TableColumn,
  //     {
  //       name : 'status',
  //       text : 'Status',
  //       width : 35
  //     } as TableColumn,
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry12 : SubForm = new SubForm({
  //   key : 'inq12',
  //   order:1200,
  //   fields : [
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'description',  
  //       label : 'Description',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'QTY',  
  //       label : 'Quantity',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.DatePicker, 
  //       key : 'date',  
  //       label : 'Date',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'status',  
  //       label : 'Status',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
  //     new BehaviorSubject<FormFieldBase>({
  //       value : '',
  //       order : 2,
  //       type : FormFieldType.TextBox, 
  //       key : 'doclink',  
  //       label : 'Documents',
  //       enabled : true,
  //       required : false,
  //       minLength : 0,
  //       maxLength : 0,
  //       regexPattern : '',
  //       width : 33,
  //       innerWidth : 98,
  //       align : 'center center'
  //     } as FormFieldBase),
      
  //   ] as BehaviorSubject<FormFieldBase>[],
  //   tableData : [],
  //   tableColumns : [
  //     {
  //         name : 'description',
  //         text : 'description',
  //         width : 35
  //     } as TableColumn,
  //     {
  //       name : 'date',
  //       text : 'Date',
  //       width : 35
  //     } as TableColumn,
  //     {
  //       name : 'status',
  //       text : 'Status',
  //       width : 35
  //     } as TableColumn,
  //   ],
  //   infoFields : [],
  //   width : 50,
  //   innerWidth : 98,
  //   align : 'center center'
  // })
  // inquiry13 : SubForm = new SubForm({
  //     key : 'inq13',
  //     title: 'Various Inquiries',
  //     order:1300,
  //     fields : [
  //       new FormFieldBase({
  //         value : '',
  //         order : 2,
  //         type : FormFieldType.TextBox, 
  //         key : 'ctmoper',  
  //         label : 'CTM Operation',
  //         enabled : true,
  //         required : false,
  //         minLength : 0,
  //         maxLength : 0,
  //         regexPattern : '',
  //         width : 33,
  //         innerWidth : 98,
  //         align : 'center center'
  //       }),
  //       new FormFieldBase>({
  //         value : '',
  //         order : 0,
  //         type : FormFieldType.TextBox,
  //         key : 'amount',
  //         label : 'amount',
  //         enabled :  true,
  //         required : false,
  //         minLength : 0,
  //         maxLength : 0,
  //         regexPattern : '',
  //         width : 33,
  //         innerWidth : 98,
  //         align : 'center center'
  //       }),
  //       new BehaviorSubject<FormFieldBase>({
  //         value : '',
  //         order : 0,
  //         type : FormFieldType.TextBox,
  //         key : 'currency',
  //         label : 'currency',
  //         enabled : true,
  //         required : false,
  //         minLength : 0,
  //         maxLength : 0,
  //         regexPattern : '',
  //         width : 33,
  //         innerWidth : 98,
  //         align : 'center center'
  //       } as FormFieldBase),
  //       new BehaviorSubject<FormFieldBase>({
  //         value : '',
  //         order : 0,
  //         type : FormFieldType.DatePicker,
  //         key : 'operdate',
  //         label : 'Operation Date',
  //         enabled : true,
  //         required : false,
  //         minLength : 0,
  //         maxLength : 0,
  //         regexPattern : '',
  //         width : 33,
  //         innerWidth : 98,
  //         align : 'center center'
  //       } as FormFieldBase)
  //     ] as BehaviorSubject<FormFieldBase>[],
  //     tableData : new BehaviorSubject<any[]>([]),
  //     tableColumns : [
  //       {
  //           name : 'ctmoper',
  //           text : 'CTM Operation',
  //           width : 25
  //       } as TableColumn,
  //       {
  //         name : 'operdate',
  //         text : 'Operation Date',
  //         width : 25
  //       } as TableColumn,
  //       {
  //         name : 'amount',
  //         text : 'amount',
  //         width : 20
  //       } as TableColumn,
  //     ],
  //     infoFields : [],
  //     width : 50,
  //     innerWidth : 98,
  //     align : 'center center'
  // })

  // inquiries = [this.inquiry1,this.inquiry2,this.inquiry3,this.inquiry4,this.inquiry5,this.inquiry6,this.inquiry7,this.inquiry8,
  //               this.inquiry9,this.inquiry10,this.inquiry11,this.inquiry12,this.inquiry13]

  // formFields : (BehaviorSubject<FormFieldBase>|SubForm)[] = [
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.Hidden,
  //     key : '_id',
  //     label : 'Call ID',
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.DatePicker,
  //     key : 'call_entry_date',
  //     label : 'Call Entry Date',
  //     order: 11,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 8,
  //     innerWidth : 80,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({ 
  //     value : '',
  //     type : FormFieldType.Hidden,
  //     key : 'vessel',
  //     label : 'Vessel ID',
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'vessel_name',
  //     label : 'Vessel Name',
  //     order: 13,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 22,
  //     innerWidth : 98,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'vessel_flag',
  //     label : 'Vessel Flag',
  //     order: 13,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 22,
  //     innerWidth : 98,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({ 
  //     value : '',
  //     type : FormFieldType.DatePicker,
  //     key : 'eta_date',
  //     label : 'ETA Date',
  //     order: 14,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 80,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.Hidden,
  //     key : 'port',
  //     label : 'Port ID'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({ 
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'port_name',
  //     label : 'Port Name',
  //     order: 16,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 22,
  //     innerWidth : 98,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({ 
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'port_anchorage',
  //     label : 'Port Anchorage',
  //     order: 17,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 21,
  //     innerWidth : 98,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.Hidden,
  //     key : 'agent',
  //     label : 'Agent ID',
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'agent_name',
  //     label : 'Agent Name',
  //     order: 19,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 22,
  //     innerWidth : 98,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'agent_person_in_charge',
  //     label : 'Agent Person In Charge',
  //     order: 19,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 22,
  //     innerWidth : 98,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.Hidden,
  //     key : 'client',
  //     label : 'Client ID'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'client_name',
  //     label : 'Client Name',
  //     order: 21,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 36,
  //     innerWidth : 98,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'client_alias',
  //     label : 'Client Alias ID',
  //     order: 22,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 6,
  //     innerWidth : 80,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'call_status',
  //     label : 'call_status',
  //     order: 0,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 50,
  //     innerWidth : 50,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'call_type',
  //     label : 'Call Type',
  //     order: 0,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 50,
  //     innerWidth : 50,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'safety_manual',
  //     label : 'Safety Manual',
  //     order: 24,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 20,
  //     innerWidth : 95,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'safety_certificate',
  //     label : 'Safety Equipment Certificate',
  //     order: 25,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 20,
  //     innerWidth : 95,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'itc',
  //     label : 'ITC',
  //     order: 26,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'ssec',
  //     label : 'SSEC',
  //     order: 28,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'nrt',
  //     label : 'NRT',
  //     order: 29,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'ert',
  //     label : 'ERT',
  //     order: 30,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'dwt',
  //     label : 'DWT',
  //     order: 31,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'breadth',
  //     label : 'BREADTH',
  //     order: 32,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'draft',
  //     label : 'DRAFT',
  //     order: 33,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'arrival_draft',
  //     label : 'Arrival DRAFT',
  //     order: 35,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'arrival_fwbob',
  //     label : 'FW BOB on Arrival',
  //     order: 36,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'arrival_sludge',
  //     label : 'Sludges on Arrival',
  //     order: 37,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'cma',
  //     label : 'Crew Medical Assistance',
  //     order: 68,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 100,
  //     innerWidth : 100,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'usr',
  //     label : 'Urgent Supplies Requirements',
  //     order:69,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 100,
  //     innerWidth : 100,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'last_rscr',
  //     label : 'Last RSCR',
  //     order: 41,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'updated_prospect_link',
  //     label : 'Updated Port Prospect',
  //     order: 45,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'updated_lineup',
  //     label : 'Updated Line Up',
  //     order: 46,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'inbound_bob',
  //     label : 'Inbound BOB',
  //     order: 47,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'outbound_fob',
  //     label : 'Outbound FOB',
  //     order: 48,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.DatePicker,
  //     key : 'entry_on_progress_date',
  //     label : 'Entry on Progress',
  //     order: 49,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'anchorage_waiting_pilot',
  //     label : 'Anchorage Waiting Pilot',
  //     order: 50,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'etb',
  //     label : 'ETB',
  //     order: 51,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'etc',
  //     label : 'ETC',
  //     order: 52,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'ets',
  //     label : 'ETS',
  //     order: 53,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({ 
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'remarks',
  //     label : 'Remarks',
  //     order: 54,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({ 
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'terminal_pisch_rate',
  //     label : 'Terminal Pisch Rate',
  //     order: 55,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'terminal_maintenance_schedule',
  //     label : 'Terminal Maintenance Schedule',
  //     order: 56,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'port_recent_accident',
  //     label : 'Port Recent Accident',
  //     order: 57,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'pilots_availability',
  //     label : 'Pilots Availability',
  //     order: 58,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'other_port_restrictions',
  //     label : 'Other New Port Restrictions',
  //     order: 59,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'military_exercise',
  //     label : 'Military Exercise',
  //     order: 60,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'warehouse_conditions',
  //     label : 'Warehouse conditions',
  //     order: 61,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'ice_concentration',
  //     label : 'Ice Concentration',
  //     order: 62,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'fog_status',
  //     label : 'Fog Status',
  //     order: 63,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
      
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'typhoons_expected',
  //     label : 'Typhoons Expected',
  //     order: 64,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({ 
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'holidays',
  //     label : 'Holidays',
  //     order: 65,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({ 
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'port_document',
  //     label : 'Port Documents',
  //     order: 66,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),
  //   new BehaviorSubject<FormFieldBase>({
  //     value : '',
  //     type : FormFieldType.TextBox,
  //     key : 'fishing_boat_risk_status',
  //     label : 'Fishing Boat Risk Status',
  //     order: 67,
  //     enabled : true,
  //     required : false,
  //     minLength : 0,
  //     maxLength : 0,
  //     regexPattern : '',
  //     width : 10,
  //     innerWidth : 90,
  //     align : 'center center'
  //   } as FormFieldBase),    
  //   ...this.inquiries
  // ]

  // tableColumns : TableColumn[] = [
  //   {
  //     name : 'name',
  //     text : 'Port Name',
  //     isFilterable : true,
  //     isSortable : true,
  //     width : 70
  //   },
  // ]

  // infoFields : InfoField[] = [
  //   {
  //     key : 'name',
  //     order : 0,
  //     label : 'Port Name',
  //     type : InfoType.Text,
  //     width : '50',
  //     innerWidth : '100',
  //     align : 'center'
  //   },
  //   {
  //     key : 'anchorage',
  //     order : 1,
  //     label : 'Anchorage',
  //     type : InfoType.Text,
  //     width : '50',
  //     innerWidth : '100',
  //     align : 'center'
  //   },
  //   {
  //     key : 'notes',
  //     order : 2,
  //     label : 'Notes',
  //     type : InfoType.Text,
  //     width : '100',
  //     innerWidth : '100',
  //     align : 'center'
  //   },
  //   {
  //     key : 'weatherLink',
  //     order : 2,
  //     label : 'Weather Link',
  //     type : InfoType.Text,
  //     width : '100',
  //     innerWidth : '100',
  //     align : 'center'
  //   }
  // ]

  // filterFields = [
  //   {
  //     key : 'name',
  //     label : 'Name',
  //     fieldType : FormFieldType.TextBox
  //   } as FilterField,
  //   {
  //     key : 'filter2',
  //     label : 'Filter 2',
  //     fieldType : FormFieldType.DatePicker
  //   } as FilterField,
  // ] as FilterField[]

  ngOnInit(): void {
  }

}
